vim.loader.enable()

require("config.options")
require("config.keymaps")
require("config.terminal")
require("config.lazy")
require("config.autocmd")
require("config.grep")
require("core.lsp")
-- vim.lsp.set_log_level("debug")
