require("plugins.fzf")
require("plugins.claude")
require("plugins.neogit")
require("plugins.diffview")
-- require("plugins.vim_fugitive")
require("plugins.treesitter")
require("plugins.colors")
require("plugins.surround")
require("plugins.oil")
require("plugins.blink")
require("plugins.gitsigns")
