require("plugins.fzf")
require("plugins.neogit")
require("plugins.treesitter")
require("plugins.colors")
require("plugins.surround")
require("plugins.oil_config")
require("plugins.blink")
require("plugins.gitsigns")
