-- Plugin specific configurations
require("plugins.themes")
require("plugins.arrow")
require("plugins.autopairs")
require("plugins.lualine")
require("plugins.fzf")
require("plugins.treesitter")
require("plugins.comments")
require("plugins.colors")
require("plugins.surround")
require("plugins.cmp")
require("plugins.mason")
require("plugins.oil")
require("plugins.notify")
